# This is a basic workflow to help you get started with Actions

name: Technical possible website CI

# Controls when the workflow will run
on:
  push:
    branches: [main]

jobs:
  ðŸ”¨ build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS }}
      - name: ðŸ’¾ Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name technicalpossiblewebpage  --auth-mode key -d '$web' -s ./webpage --overwrite=True
      - name: ðŸ’£ Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "Technical-Webpage-CDN" --name "technical-webpage" --resource-group "technical-possible"
      # Azure logout
      - name: ðŸ“´ logout
        run: |
          az logout
        if: always()
